import 'server-only';

/**
 * Shared between /api/gmail/connect (sets it) and /api/gmail/callback (reads it) — lives here
 * rather than as a named export from either route.ts, since Next's App Router only allows a
 * route file to export recognized handlers (GET/POST/etc.) and a small config allowlist; an
 * arbitrary named export like this one fails `next`'s generated route-type validation (only
 * surfaces once `.next/types` has actually been generated by a dev/build run, not on a bare
 * `tsc --noEmit` against a fresh checkout).
 */
export const OAUTH_STATE_COOKIE = 'gmail_oauth_state';

/** Kept as its own explicit env var rather than derived from NEXT_PUBLIC_APP_URL at runtime, so
 * the Google Cloud Console "Authorized redirect URI" entry has one canonical value per
 * environment, independently settable for a preview deployment if ever needed. */
export function getGoogleOAuthRedirectUri(): string {
  const uri = process.env.GOOGLE_OAUTH_REDIRECT_URI;
  if (!uri) {
    throw new Error('GOOGLE_OAUTH_REDIRECT_URI is not set — required for Gmail OAuth.');
  }
  return uri;
}
