import type { DetectedField, JobExtractionPayload, ReviewableField } from '@career-os/shared';
import type { FillResult } from '../content-script/fill/fill-engine';

/**
 * chrome.runtime.sendMessage is a broadcast — it reaches every listener in the extension (every
 * open popup instance, the background worker), with no built-in way to target "just the popup
 * that asked" or "just the tab I injected into." Every request/result pair below carries a
 * requestId (crypto.randomUUID(), generated by the popup when it starts the operation) so a
 * result can be matched back to the specific operation that asked for it — the popup hooks
 * (useAnalysis.ts, useAutofill.ts) track which requestId is currently pending and discard any
 * result whose requestId doesn't match, which is what makes a late result from a closed-and-
 * reopened popup, a previous tab, or a duplicate click safe to ignore instead of silently
 * overwriting the current job's state (docs/IMPLEMENTATION_PLAN.md Phase 4D).
 */

/** Popup -> background: user clicked "Analyze Job". */
export interface AnalyzeJobRequest {
  type: 'ANALYZE_JOB';
  requestId: string;
}

/** Content script -> background -> popup: the combined extraction + field-detection result. */
export interface AnalyzeJobResult {
  type: 'ANALYZE_JOB_RESULT';
  requestId: string;
  job: JobExtractionPayload;
  fields: DetectedField[];
}

export interface AnalyzeJobError {
  type: 'ANALYZE_JOB_ERROR';
  requestId: string;
  message: string;
}

/**
 * Popup -> background -> content script: fill only these fields (Phase 4B). Carries the popup's
 * own ReviewableField objects (already-typed, reused rather than duplicated into a bespoke DTO)
 * — the fill engine independently re-validates approvalState/reviewState/classification on the
 * receiving end regardless of what this payload claims, since it runs in a separate script
 * execution reached only via this message, not a direct call the popup's own guards could gate.
 */
export interface AutofillApprovedFieldsRequest {
  type: 'AUTOFILL_APPROVED_FIELDS';
  requestId: string;
  fields: ReviewableField[];
}

/** Content script -> popup: per-field fill outcomes. */
export interface AutofillResult {
  type: 'AUTOFILL_RESULT';
  requestId: string;
  results: FillResult[];
}

export interface AutofillError {
  type: 'AUTOFILL_ERROR';
  requestId: string;
  message: string;
}

export type ExtensionMessage =
  | AnalyzeJobRequest
  | AnalyzeJobResult
  | AnalyzeJobError
  | AutofillApprovedFieldsRequest
  | AutofillResult
  | AutofillError;

/**
 * Sent from the Career OS web app (docs/EXTENSION_DESIGN.md §4's one-time token handoff) via
 * chrome.runtime.sendMessage, not from within the extension itself — kept separate from
 * ExtensionMessage above so the two message spaces (internal vs. externally_connectable) can't
 * be confused with each other. The background's onMessageExternal listener validates this shape
 * strictly before writing anything to storage.
 */
export interface ExternalTokenHandoffMessage {
  type: 'CAREER_OS_EXTENSION_TOKEN';
  token: string;
  expiresAt: string;
}

export function isExternalTokenHandoffMessage(
  message: unknown,
): message is ExternalTokenHandoffMessage {
  return (
    typeof message === 'object' &&
    message !== null &&
    (message as { type?: unknown }).type === 'CAREER_OS_EXTENSION_TOKEN' &&
    typeof (message as { token?: unknown }).token === 'string' &&
    typeof (message as { expiresAt?: unknown }).expiresAt === 'string'
  );
}
