import type { NextAction } from '../schemas/next-action';

/**
 * Turns a `NextAction` into UI text — deliberately separate from `next-action-rules.ts` (Phase
 * 5C.1A: "consider whether title/reason should be generated by a formatter instead of stored in
 * the core domain object"), so wording changes never touch the rule engine and the rule engine's
 * own tests never need to assert exact prose. Pure string formatting only — no new facts, no
 * dates beyond what the `NextAction` already carries.
 *
 * Every `reason` string here follows docs/IMPLEMENTATION_PLAN.md "Phase 5C.1I"'s explicit
 * fact-vs-recommendation rule: a real persisted date is stated as a fact ("you applied N days
 * ago"), and the *absence* of a newer signal is stated as an observation ("Career OS has not
 * detected a newer update") — but the suggestion itself ("consider following up") is always
 * phrased as Career OS's own recommendation, never as an employer expectation, promise, or
 * deadline. Nothing here ever says "overdue," "late," or names a specific due date, because
 * this codebase never persists one (see `NextAction.dueAt`'s own doc comment).
 */
export interface FormattedNextAction {
  title: string;
  reason: string;
}

export function formatNextAction(action: NextAction): FormattedNextAction {
  switch (action.type) {
    case 'REVIEW_UNRESOLVED_FIELDS':
      return {
        title: 'Review unresolved fields',
        reason:
          'Some fields on this application still need your review before it is ready.',
      };
    case 'COMPLETE_APPLICATION':
      return {
        title: 'Continue this application',
        reason: 'This application has not been started yet — pick it up when ready.',
      };
    case 'MARK_APPLIED':
      return {
        title: 'Finish and mark as applied',
        reason:
          "Everything Career OS could help review is resolved — submit on the employer's site, then mark it applied.",
      };
    case 'REVIEW_ACTION_REQUIRED':
      return {
        title: 'Review employer action required',
        reason: 'The employer is asking for something on this application.',
      };
    case 'COMPLETE_ASSESSMENT':
      return {
        title: 'Complete the assessment',
        reason: 'An assessment or task is pending for this application.',
      };
    case 'PREPARE_INTERVIEW':
      return {
        title: 'Prepare for the interview',
        reason: 'This application has moved to the interview stage.',
      };
    case 'REVIEW_OFFER':
      return {
        title: 'Review the offer',
        reason: 'This application has an offer to review.',
      };
    case 'CONSIDER_FOLLOW_UP': {
      const days = action.daysSinceApplied;
      return {
        title: 'Consider following up',
        reason:
          days !== null
            ? `You applied ${days} day${days === 1 ? '' : 's'} ago and Career OS has not detected a newer employer update. Career OS suggests following up — this is a recommendation, not a known employer deadline.`
            : 'Career OS suggests following up — this is a recommendation, not a known employer deadline.',
      };
    }
    case 'REVIEW_APPLICATION':
      return {
        title: 'Review this application',
        reason: "This application's status could not be classified automatically.",
      };
    case 'NO_ACTION':
      return {
        title: 'No action needed',
        reason: 'Nothing currently needs your attention on this application.',
      };
  }
}
